# Generated by Django 2.1.4 on 2020-05-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carton_cloud_client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.IntegerField(unique=True)),
                ('c_name', models.CharField(max_length=64)),
                ('c_email', models.CharField(max_length=128)),
                ('c_telephone', models.CharField(max_length=64)),
                ('c_customer_charge_name', models.CharField(max_length=32)),
                ('c_active', models.CharField(max_length=32)),
                ('c_register_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
