# Generated by Django 2.1.4 on 2020-05-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('warehouse', '0003_auto_20200520_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containers',
            name='ctnr_special',
        ),
        migrations.AddField(
            model_name='containers',
            name='ctnr_active',
            field=models.CharField(default=1, max_length=8),
        ),
    ]
