# Generated by Django 2.1.4 on 2020-05-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientCompanyCreditRating', models.CharField(default='10', max_length=16, null=True)),
                ('clientCompanyName', models.CharField(max_length=128, unique=True)),
                ('clientCompanyContactPerson', models.CharField(default='0', max_length=64, null=True)),
                ('clientCompanyContactMobile', models.CharField(default='0', max_length=64)),
                ('clientCompanyAddress', models.CharField(default='NZ', max_length=128)),
                ('clientCompanyEmail', models.CharField(default='0', max_length=128)),
                ('clientCompanyServiceOnHold', models.BooleanField(default=False, null=True)),
                ('NZBN', models.CharField(default='0', max_length=64, unique=True)),
            ],
        ),
    ]
