# Generated by Django 2.1.4 on 2020-05-22 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('staff_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField(auto_now=True)),
                ('end_time', models.TimeField(auto_now=True)),
                ('hours_today', models.CharField(default=0, max_length=64)),
                ('record_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=32)),
                ('s_mobilenumber', models.CharField(default='', max_length=64, unique=True)),
                ('s_isworking', models.BooleanField(default=False)),
                ('working_hour_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff_user.hours')),
            ],
        ),
        migrations.DeleteModel(
            name='staff_user',
        ),
    ]
