# Generated by Django 2.1.4 on 2020-05-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('staff_user', '0002_auto_20200522_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='working_hour_id',
        ),
        migrations.AddField(
            model_name='hours',
            name='h_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='s_mobilenumber',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
