# Generated by Django 2.1.4 on 2020-05-23 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_user', '0002_auto_20200523_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='end_time',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='hours',
            name='start_time',
            field=models.CharField(default=datetime.datetime.now, max_length=32),
        ),
    ]
