# Generated by Django 2.1.4 on 2020-05-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('staff_user', '0003_auto_20200523_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='record_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hours',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
