# Generated by Django 2.1.4 on 2020-05-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('staff_user', '0004_auto_20200523_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='start_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
