# Generated by Django 2.1.4 on 2020-05-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('staff_user', '0005_auto_20200523_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='record_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
