# Generated by Django 2.1.4 on 2020-05-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('staff_user', '0006_auto_20200523_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='hours_today',
            field=models.TimeField(default=0),
        ),
    ]
